
title = "Kevin Liao"
author = "Kevin"
copyright = "2020-2022"
description = "For Love"
profilePicture = "images/profile.jpg"
keywords = ""
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
#contactFormAction = "https://formspree.io/f/your-form-hash-here"
# Google Site Verify
#googleSiteVerify = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
singleDateFormat = "2006/01/02"
indexDateFormat = "2006/01/02"
listDateFormat = "2006/01/02"
#date formate
# Commento Comments
# CommentoURL = "https://commento.example.com/js/commento.js"
# Read More links for truncated summaries
readMore = true
# postSectionName = "blog"


[simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links

[[socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/imkevinliao/imkevinliao.github.io"


[[socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:im.kevinliao@gmail.com"
